// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsrvjzwizemkecdlupzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzcnZqendpemVta2VjZGx1cHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODczMDQsImV4cCI6MjA2MzU2MzMwNH0.oiEH3QURtCUE8E-tri_ggEVN0xsVgVZ2RaY50EumJhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);